-- Makka Halal Meat — Aisle 1 catalog/category update
-- Run in Supabase SQL editor AFTER deploying v22 aisle-1 build.
begin;
update public.products set name='Frozen Samosas', department='grocery', category='Frozen', subcategory='Frozen' where id=7;
update public.products set name='Basmati Rice 10 lb', department='grocery', category='Rice & Grains', subcategory='Rice' where id=8;
update public.products set name='Laxmi Garam Masala Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=9;
update public.products set name='Laxmi Cinnamon Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=10;
update public.products set name='Laxmi Fenugreek Whole', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=11;
update public.products set name='Laxmi Crushed Red Chili', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=12;
update public.products set name='Laxmi Chili Powder Kashmiri', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=13;
update public.products set name='Laxmi Turmeric Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=14;
update public.products set name='Goya Adobo All Purpose Seasoning', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=15;
update public.products set name='Parsley Flakes', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=16;
update public.products set name='Ziyad Cumin Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=17;
update public.products set name='Laxmi Ground Allspice', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=18;
update public.products set name='Laxmi Fennel Seeds', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=19;
update public.products set name='Laxmi Cumin Powder large', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=20;
update public.products set name='Badia Garlic Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=21;
update public.products set name='Badia Onion Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=22;
update public.products set name='Kinder''s No Salt Seasoning', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=23;
update public.products set name='Old Bay Seasoning', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=24;
update public.products set name='Chili Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=25;
update public.products set name='Crushed Red Pepper', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=26;
update public.products set name='Sesame Seeds', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=27;
update public.products set name='Cumin', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=28;
update public.products set name='Cilantro', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=29;
update public.products set name='Lemon Pepper', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=30;
update public.products set name='Curry Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=31;
update public.products set name='Ginger', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=32;
update public.products set name='Cayenne Pepper', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=33;
update public.products set name='Garlic', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=34;
update public.products set name='Turmeric', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=35;
update public.products set name='Paprika', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=36;
update public.products set name='Onion', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=37;
update public.products set name='Cinnamon', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=38;
update public.products set name='Fennel', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=39;
update public.products set name='Fine Black Pepper', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=40;
update public.products set name='Laxmi Coriander Seeds', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=41;
update public.products set name='Laxmi Garam Masala', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=42;
update public.products set name='Laxmi Coriander Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=43;
update public.products set name='Laxmi Methi Seed', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=44;
update public.products set name='Ziyad Falafel Mix', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=45;
update public.products set name='Lawry''s Seasoned Salt', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=46;
update public.products set name='Tone''s Ground Ginger', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=47;
update public.products set name='Thyme Leaves', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=48;
update public.products set name='Goya Adobo Seasoning', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=49;
update public.products set name='Badia Garlic Powder', department='grocery', category='Seasoning & Spices', subcategory='Spices & Seasoning' where id=50;
update public.products set name='Laxmi Coconut Powder', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=51;
update public.products set name='Bisquick Pancake & Baking Mix', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=52;
update public.products set name='Argo Corn Starch', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=53;
update public.products set name='Organic All-Purpose Flour', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=54;
update public.products set name='Gold Medal All Purpose Flour', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=55;
update public.products set name='White Lily Flour', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=56;
update public.products set name='Five Roses Flour', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=57;
update public.products set name='Rice Flour', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=58;
update public.products set name='White Corn Flour', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=59;
update public.products set name='Domino Granulated Sugar', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=60;
update public.products set name='Pure Cane Sugar large bag', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=61;
update public.products set name='Sugar in the Raw Turbinado Cane Sugar', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=62;
update public.products set name='Madi Pan Pinton / baking product', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=63;
update public.products set name='Barilla Tri-Color Rotini', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=64;
update public.products set name='Barilla Tri-Color Penne', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=65;
update public.products set name='La Moderna Pasta assorted', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=66;
update public.products set name='Spaghetti / pasta bags', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=67;
update public.products set name='Lord del Sud Organic Spaghetti 20x1lb case', department='grocery', category='Pasta & Noodles', subcategory='Baking / Pasta' where id=68;
update public.products set name='Amber Basmati Rice Premium Grade No.1 Extra Clean 10 lb', department='grocery', category='Rice & Grains', subcategory='Rice' where id=69;
update public.products set name='Amber Basmati Rice Premium Grade No.1 Extra Clean 20 lb', department='grocery', category='Rice & Grains', subcategory='Rice' where id=70;
update public.products set name='Bazarac Basmati Sela Parboiled Grade A 10 lb', department='grocery', category='Rice & Grains', subcategory='Rice' where id=71;
update public.products set name='Bazarac Basmati Sela Parboiled Grade A 20 lb', department='grocery', category='Rice & Grains', subcategory='Rice' where id=72;
update public.products set name='Royal Basmati Rice', department='grocery', category='Rice & Grains', subcategory='Rice' where id=73;
update public.products set name='Hunt''s Tomato Sauce large can', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=74;
update public.products set name='Tomato Paste large can', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=75;
update public.products set name='Nina Italian Peeled Tomatoes', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=76;
update public.products set name='Organic Diced Tomatoes', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=77;
update public.products set name='Organic Tomato Sauce', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=78;
update public.products set name='Frank''s RedHot Original', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=79;
update public.products set name='Heinz Tomato Ketchup', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=80;
update public.products set name='Heinz Yellow Mustard', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=81;
update public.products set name='Hellmann''s Real Mayonnaise', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=82;
update public.products set name='Tamam Tomato Paste jar', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=83;
update public.products set name='Ragu Pasta Sauce assorted', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=84;
update public.products set name='Prego Pasta Sauce assorted', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=85;
update public.products set name='Texas Pete Hot Sauce', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=86;
update public.products set name='Chick-fil-A Sauce bottle', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=87;
update public.products set name='Biscoff Cookie Butter', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=88;
update public.products set name='Jif Creamy Peanut Butter', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=89;
update public.products set name='Creamy Peanut Butter', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=90;
update public.products set name='Rani Peanut Butter', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=91;
update public.products set name='Goya Adobo assorted', department='grocery', category='Condiments & Sauces', subcategory='Sauces & Condiments' where id=92;
update public.products set name='Del Monte Cut Green Beans', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=93;
update public.products set name='Del Monte Whole Kernel Corn', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=94;
update public.products set name='Del Monte Peas', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=95;
update public.products set name='Popeye Spinach', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=96;
update public.products set name='Veg-All Mixed Vegetables', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=97;
update public.products set name='Sultan Canned vegetables assorted', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=98;
update public.products set name='Bush''s Beans assorted', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=99;
update public.products set name='Goya Beans assorted', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=100;
update public.products set name='Goya Tuna / canned seafood assorted', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=101;
update public.products set name='Portofino Tuna', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=102;
update public.products set name='Pink Salmon', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=103;
update public.products set name='StarKist Tuna', department='grocery', category='Canned Goods', subcategory='Canned Goods' where id=104;
update public.products set name='Shan Mutton Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=105;
update public.products set name='Shan Sindhi Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=106;
update public.products set name='Shan Fish Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=107;
update public.products set name='Shan Bombay Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=108;
update public.products set name='Shan Malay Chicken Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=109;
update public.products set name='Shan Karachi Beef Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=110;
update public.products set name='Shan Pilau Biryani', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=111;
update public.products set name='Shan Chicken Handi', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=112;
update public.products set name='Shan Paya', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=113;
update public.products set name='Shan Chicken Ginger', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=114;
update public.products set name='Shan Murgh Cholay', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=115;
update public.products set name='Shan Daal Masala', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=116;
update public.products set name='Shan Chaat Masala', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=117;
update public.products set name='Shan Meat & Vegetable', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=118;
update public.products set name='Shan Shami Kabab', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=119;
update public.products set name='Shan Chicken Curry', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=120;
update public.products set name='Shan Korma', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=121;
update public.products set name='Shan Haleem', department='grocery', category='Pantry', subcategory='Recipe Mix' where id=122;
update public.products set name='Mazola Corn Oil large', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=123;
update public.products set name='Ottavio Organic High Oleic Sunflower Oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=124;
update public.products set name='Laxmi Cold Pressed Sesame Oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=125;
update public.products set name='Pompeian Extra Virgin Olive Oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=126;
update public.products set name='Extra Virgin Olive Oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=127;
update public.products set name='Supremo Italiano Extra Virgin Olive Oil tin', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=128;
update public.products set name='Wesson Canola Oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=129;
update public.products set name='Wesson Vegetable Oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=130;
update public.products set name='Crisco Vegetable Shortening / oil', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=131;
update public.products set name='Ghee', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=132;
update public.products set name='Ghee jars', department='grocery', category='Oils & Vinegar', subcategory='Cooking Oil & Ghee' where id=133;
update public.products set name='Ahmad Tea Cardamom Tea', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=134;
update public.products set name='Ahmad Tea English Tea No.1', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=135;
update public.products set name='Ahmad Tea Earl Grey Tea', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=136;
update public.products set name='Ahmad Tea Aromatic Earl Grey', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=137;
update public.products set name='Ahmad Tea Ceylon Tea', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=138;
update public.products set name='Ahmad Tea Imperial Blend', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=139;
update public.products set name='Ahmad Tea Kalami Assam', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=140;
update public.products set name='Ahmad Tea English Breakfast', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=141;
update public.products set name='Pocas Instant Honey Ginger Tea', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=142;
update public.products set name='China Slim Tea Herbal Tea Delight', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=143;
update public.products set name='3 Ballerina Herbal Tea', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=144;
update public.products set name='Green Fresh Herbal Dieter''s Tea', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=145;
update public.products set name='Jacobs Kronung Coffee', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=146;
update public.products set name='Nescafe Instant Coffee', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=147;
update public.products set name='Maxwell House Coffee', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=148;
update public.products set name='Folgers Coffee', department='grocery', category='Tea & Coffee', subcategory='Tea & Coffee' where id=149;
update public.products set name='Tri-C Instant Drink Powder assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=150;
update public.products set name='Vimto Fruit Cordial', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=151;
update public.products set name='Frooti Mango / fruit drink large', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=152;
update public.products set name='Arabican Fruit drink cartons assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=153;
update public.products set name='Vita Malt Classic', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=154;
update public.products set name='Vita Malt Ginger', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=155;
update public.products set name='Power Malt Energy drink', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=156;
update public.products set name='Kesar Mango Pulp canned', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=157;
update public.products set name='Bird''s Custard Powder', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=158;
update public.products set name='Langers Organic Mango Nectar gallon', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=159;
update public.products set name='Fanta Orange glass bottle case', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=160;
update public.products set name='Jarritos Case assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=161;
update public.products set name='Coca-Cola 2 liter', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=162;
update public.products set name='Sprite 2 liter', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=163;
update public.products set name='Pepsi 2 liter', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=164;
update public.products set name='Fanta 2 liter', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=165;
update public.products set name='Fiji Bottled water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=166;
update public.products set name='Deer Park Bottled water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=167;
update public.products set name='Evian Bottled water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=168;
update public.products set name='Acqua Panna Bottled water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=169;
update public.products set name='Dasani Bottled water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=170;
update public.products set name='Aquafina Bottled water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=171;
update public.products set name='Powerade Assorted flavors', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=172;
update public.products set name='Gatorade Assorted flavors', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=173;
update public.products set name='Gatorade Larger bottle assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=174;
update public.products set name='Perrier Glass bottle', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=175;
update public.products set name='Topo Chico Glass bottle', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=176;
update public.products set name='Mogu Mogu Assorted flavors', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=177;
update public.products set name='Coca-Cola Can', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=178;
update public.products set name='Mountain Dew Can', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=179;
update public.products set name='Fanta Can assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=180;
update public.products set name='Red Bull Can', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=181;
update public.products set name='Coca-Cola 20 oz bottle', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=182;
update public.products set name='Sprite 20 oz bottle', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=183;
update public.products set name='Pepsi 20 oz bottle', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=184;
update public.products set name='Dr Pepper Bottle/can', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=185;
update public.products set name='7UP 20 oz bottle', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=186;
update public.products set name='Fanta 20 oz bottle assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=187;
update public.products set name='Sunkist Bottle/can assorted', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=188;
update public.products set name='Jarritos Assorted glass bottles', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=189;
update public.products set name='FOCO Coconut Juice', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=190;
update public.products set name='FOCO Tamarind Drink', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=191;
update public.products set name='Jumex Coconut Water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=192;
update public.products set name='FOCO Coconut Water', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=193;
update public.products set name='Farmer''s Aloe Vera Aloe Vera Drink', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=194;
update public.products set name='Tropical Fantasy Assorted flavors', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=195;
update public.products set name='Ocean Spray Cranberry Juice', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=196;
update public.products set name='Organic Lemonade', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=197;
update public.products set name='Veryfine Fruit Punch', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=198;
update public.products set name='Langers Tart Cherry Pineapple', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=199;
update public.products set name='Mott''s 100% Apple Juice', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=200;
update public.products set name='Hawaiian Punch Large jug', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=201;
update public.products set name='Langers Mango Nectar', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=202;
update public.products set name='Sunberry Farms Guava Nectar', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=203;
update public.products set name='Sunberry Farms Orange Passion Nectar', department='grocery', category='Drinks & Beverages', subcategory='Drinks' where id=204;
update public.products set name='Sour Bears Candy', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=205;
update public.products set name='Cherry Gummies', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=206;
update public.products set name='Peach Rings', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=207;
update public.products set name='Gummy Sharks', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=208;
update public.products set name='Gummy Worms', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=209;
update public.products set name='Gushers Variety Pack', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=210;
update public.products set name='Kopiko Coffee Candy assorted', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=211;
update public.products set name='Al Safa Crispy Rice Squares', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=212;
update public.products set name='Biscoff Cookies', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=213;
update public.products set name='Cake Rusk Assorted boxes', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=214;
update public.products set name='Parle-G / assorted Biscuits', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=215;
update public.products set name='Cream Biscuits assorted', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=216;
update public.products set name='Baklava / boxed sweets', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=217;
update public.products set name='Dates / sweets gift box', department='candy', category='Candy & Sweets', subcategory='Snacks & Sweets' where id=218;
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 7 and coalesce(description,'') = '';
update public.products set description = 'A pantry grain staple for rice dishes, sides, pilafs, and traditional family meals.' where id = 8 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 9 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 10 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 11 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 12 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 13 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 14 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 15 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 16 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 17 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 18 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 19 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 20 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 21 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 22 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 23 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 24 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 25 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 26 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 27 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 28 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 29 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 30 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 31 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 32 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 33 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 34 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 35 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 36 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 37 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 38 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 39 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 40 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 41 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 42 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 43 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 44 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 45 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 46 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 47 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 48 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 49 and coalesce(description,'') = '';
update public.products set description = 'A pantry seasoning or spice for adding flavor and aroma to everyday cooking, rice dishes, meats, sauces, and traditional recipes.' where id = 50 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 51 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 52 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 53 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 54 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 55 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 56 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 57 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 58 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 59 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 60 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 61 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 62 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 63 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 64 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 65 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 66 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 67 and coalesce(description,'') = '';
update public.products set description = 'A pantry staple for preparing pasta or noodle dishes, soups, sides, and family meals.' where id = 68 and coalesce(description,'') = '';
update public.products set description = 'A pantry grain staple for rice dishes, sides, pilafs, and traditional family meals.' where id = 69 and coalesce(description,'') = '';
update public.products set description = 'A pantry grain staple for rice dishes, sides, pilafs, and traditional family meals.' where id = 70 and coalesce(description,'') = '';
update public.products set description = 'A pantry grain staple for rice dishes, sides, pilafs, and traditional family meals.' where id = 71 and coalesce(description,'') = '';
update public.products set description = 'A pantry grain staple for rice dishes, sides, pilafs, and traditional family meals.' where id = 72 and coalesce(description,'') = '';
update public.products set description = 'A pantry grain staple for rice dishes, sides, pilafs, and traditional family meals.' where id = 73 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 74 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 75 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 76 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 77 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 78 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 79 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 80 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 81 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 82 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 83 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 84 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 85 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 86 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 87 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 88 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 89 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 90 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 91 and coalesce(description,'') = '';
update public.products set description = 'A flavorful sauce or condiment for cooking, dipping, marinating, dressing, or serving with meals.' where id = 92 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 93 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 94 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 95 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 96 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 97 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 98 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 99 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 100 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 101 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 102 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 103 and coalesce(description,'') = '';
update public.products set description = 'A convenient pantry item for quick meals, sides, soups, stews, salads, and everyday recipes.' where id = 104 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 105 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 106 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 107 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 108 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 109 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 110 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 111 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 112 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 113 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 114 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 115 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 116 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 117 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 118 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 119 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 120 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 121 and coalesce(description,'') = '';
update public.products set description = 'A grocery staple selected for everyday meals, snacks, and pantry use.' where id = 122 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 123 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 124 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 125 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 126 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 127 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 128 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 129 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 130 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 131 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 132 and coalesce(description,'') = '';
update public.products set description = 'A kitchen staple for cooking, frying, dressing, marinating, or finishing a variety of dishes.' where id = 133 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 134 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 135 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 136 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 137 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 138 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 139 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 140 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 141 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 142 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 143 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 144 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 145 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 146 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 147 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 148 and coalesce(description,'') = '';
update public.products set description = 'A tea or coffee selection for preparing a warm, flavorful beverage at home.' where id = 149 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 150 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 151 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 152 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 153 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 154 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 155 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 156 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 157 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 158 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 159 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 160 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 161 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 162 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 163 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 164 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 165 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 166 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 167 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 168 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 169 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 170 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 171 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 172 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 173 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 174 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 175 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 176 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 177 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 178 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 179 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 180 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 181 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 182 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 183 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 184 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 185 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 186 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 187 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 188 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 189 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 190 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 191 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 192 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 193 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 194 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 195 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 196 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 197 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 198 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 199 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 200 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 201 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 202 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 203 and coalesce(description,'') = '';
update public.products set description = 'A refreshing beverage option for serving chilled or enjoying with meals.' where id = 204 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 205 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 206 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 207 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 208 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 209 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 210 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 211 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 212 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 213 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 214 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 215 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 216 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 217 and coalesce(description,'') = '';
update public.products set description = 'A sweet snack or treat for enjoying on its own, sharing, or serving with tea and coffee.' where id = 218 and coalesce(description,'') = '';
commit;
