insert into public.products (id, name, department, category, subcategory, price, unit, image, emoji, brand, active) values
(7,'Frozen Samosas','grocery','Frozen','Frozen',7.99,'each','','🥟','Makka Halal Meat',true),
(8,'Basmati Rice 10 lb','grocery','Pantry','Rice',17.99,'each','','🍚','Makka Halal Meat',true),
(9,'Laxmi Garam Masala Powder','grocery','Pantry','Spices & Seasoning',6.99,'each','','🧂','Laxmi',true),
(10,'Laxmi Cinnamon Powder','grocery','Pantry','Spices & Seasoning',6.99,'each','','🧂','Laxmi',true),
(11,'Laxmi Fenugreek Whole','grocery','Pantry','Spices & Seasoning',6.99,'each','','🛒','Laxmi',true),
(12,'Laxmi Crushed Red Chili','grocery','Pantry','Spices & Seasoning',6.99,'each','','🛒','Laxmi',true),
(13,'Laxmi Chili Powder Kashmiri','grocery','Pantry','Spices & Seasoning',6.99,'each','','🧂','Laxmi',true),
(14,'Laxmi Turmeric Powder','grocery','Pantry','Spices & Seasoning',6.99,'each','','🧂','Laxmi',true),
(15,'Goya Adobo All Purpose Seasoning','grocery','Pantry','Spices & Seasoning',3.99,'each','','🧂','Goya',true),
(16,'Member''s Mark Parsley Flakes','grocery','Pantry','Spices & Seasoning',3.99,'each','','🛒','Member''s Mark',true),
(17,'Ziyad Cumin Powder','grocery','Pantry','Spices & Seasoning',3.99,'each','','🧂','Ziyad',true),
(18,'Laxmi Ground Allspice','grocery','Pantry','Spices & Seasoning',12.99,'each','','🧂','Laxmi',true),
(19,'Laxmi Fennel Seeds','grocery','Pantry','Spices & Seasoning',6.99,'each','','🛒','Laxmi',true),
(20,'Laxmi Cumin Powder large','grocery','Pantry','Spices & Seasoning',6.99,'each','','🧂','Laxmi',true),
(21,'Badia Garlic Powder','grocery','Pantry','Spices & Seasoning',3.99,'each','','🧂','Badia',true),
(22,'Badia Onion Powder','grocery','Pantry','Spices & Seasoning',3.99,'each','','🧂','Badia',true),
(23,'Kinder''s No Salt Seasoning','grocery','Pantry','Spices & Seasoning',3.99,'each','','🧂','Kinder''s',true),
(24,'Old Bay Seasoning','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Old Bay',true),
(25,'Member''s Mark Chili Powder','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(26,'Member''s Mark Crushed Red Pepper','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(27,'Member''s Mark Sesame Seeds','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Member''s Mark',true),
(28,'Member''s Mark Cumin','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(29,'Member''s Mark Cilantro','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Member''s Mark',true),
(30,'Member''s Mark Lemon Pepper','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(31,'Member''s Mark Curry Powder','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(32,'Member''s Mark Ginger','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Member''s Mark',true),
(33,'Member''s Mark Cayenne Pepper','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(34,'Member''s Mark Garlic','grocery','Pantry','Spices & Seasoning',NULL,'','','🥬','Member''s Mark',true),
(35,'Member''s Mark Turmeric','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(36,'Member''s Mark Paprika','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Member''s Mark',true),
(37,'Member''s Mark Onion','grocery','Pantry','Spices & Seasoning',NULL,'','','🥬','Member''s Mark',true),
(38,'Member''s Mark Cinnamon','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(39,'Member''s Mark Fennel','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Member''s Mark',true),
(40,'Member''s Mark Fine Black Pepper','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Member''s Mark',true),
(41,'Laxmi Coriander Seeds','grocery','Pantry','Spices & Seasoning',2.99,'each','','🛒','Laxmi',true),
(42,'Laxmi Garam Masala','grocery','Pantry','Spices & Seasoning',4.99,'each','','🧂','Laxmi',true),
(43,'Laxmi Coriander Powder','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Laxmi',true),
(44,'Laxmi Methi Seed','grocery','Pantry','Spices & Seasoning',4.99,'each','','🛒','Laxmi',true),
(45,'Ziyad Falafel Mix','grocery','Pantry','Spices & Seasoning',3.99,'each','','🛒','Ziyad',true),
(46,'Lawry''s Seasoned Salt','grocery','Pantry','Spices & Seasoning',3.99,'each','','🧂','Lawry''s',true),
(47,'Tone''s Ground Ginger','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Tone''s',true),
(48,'Member''s Mark Thyme Leaves','grocery','Pantry','Spices & Seasoning',NULL,'','','🛒','Member''s Mark',true),
(49,'Goya Adobo Seasoning','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Goya',true),
(50,'Badia Garlic Powder','grocery','Pantry','Spices & Seasoning',NULL,'','','🧂','Badia',true),
(51,'Laxmi Coconut Powder','grocery','Pantry','Baking / Pasta',2.99,'each','','🧂','Laxmi',true),
(52,'Bisquick Pancake & Baking Mix','grocery','Pantry','Baking / Pasta',11.99,'each','','🛒','Bisquick',true),
(53,'Argo Corn Starch','grocery','Pantry','Baking / Pasta',2.49,'each','','🛒','Argo',true),
(54,'Kirkland Organic All-Purpose Flour','grocery','Pantry','Baking / Pasta',11.99,'each','','🛒','Kirkland',true),
(55,'Gold Medal All Purpose Flour','grocery','Pantry','Baking / Pasta',10.99,'each','','🛒','Gold Medal',true),
(56,'White Lily Flour','grocery','Pantry','Baking / Pasta',6.99,'each','','🛒','White Lily',true),
(57,'Five Roses Flour','grocery','Pantry','Baking / Pasta',NULL,'','','🛒','Five Roses',true),
(58,'Rice Flour','grocery','Pantry','Baking / Pasta',1.99,'each','','🍚','Various',true),
(59,'White Corn Flour','grocery','Pantry','Baking / Pasta',NULL,'','','🛒','Various',true),
(60,'Domino Granulated Sugar','grocery','Pantry','Baking / Pasta',NULL,'','','🛒','Domino',true),
(61,'Pure Cane Sugar large bag','grocery','Pantry','Baking / Pasta',15.0,'each','','🧼','Various',true),
(62,'Sugar in the Raw Turbinado Cane Sugar','grocery','Pantry','Baking / Pasta',NULL,'','','🛒','Sugar in the Raw',true),
(63,'Madi Pan Pinton / baking product','grocery','Pantry','Baking / Pasta',8.99,'each','','🛒','Madi',true),
(64,'Barilla Tri-Color Rotini','grocery','Pantry','Baking / Pasta',1.69,'each','','🛒','Barilla',true),
(65,'Barilla Tri-Color Penne','grocery','Pantry','Baking / Pasta',1.69,'each','','🛒','Barilla',true),
(66,'La Moderna Pasta assorted','grocery','Pantry','Baking / Pasta',1.29,'each','','🛒','La Moderna',true),
(67,'Spaghetti / pasta bags','grocery','Pantry','Baking / Pasta',NULL,'','','🧼','Various',true),
(68,'Lord del Sud Organic Spaghetti 20x1lb case','grocery','Pantry','Baking / Pasta',NULL,'','','🛒','Lord del Sud',true),
(69,'Amber Basmati Rice Premium Grade No.1 Extra Clean 10 lb','grocery','Pantry','Rice',10.99,'each','','🍚','Amber',true),
(70,'Amber Basmati Rice Premium Grade No.1 Extra Clean 20 lb','grocery','Pantry','Rice',18.99,'each','','🍚','Amber',true),
(71,'Bazarac Basmati Sela Parboiled Grade A 10 lb','grocery','Pantry','Rice',12.99,'each','','🛒','Bazarac',true),
(72,'Bazarac Basmati Sela Parboiled Grade A 20 lb','grocery','Pantry','Rice',24.99,'each','','🛒','Bazarac',true),
(73,'Royal Basmati Rice','grocery','Pantry','Rice',NULL,'','','🍚','Royal',true),
(74,'Hunt''s Tomato Sauce large can','grocery','Pantry','Sauces & Condiments',7.99,'each','','🥬','Hunt''s',true),
(75,'Member''s Mark Tomato Paste large can','grocery','Pantry','Sauces & Condiments',10.99,'each','','🥬','Member''s Mark',true),
(76,'Nina Italian Peeled Tomatoes','grocery','Pantry','Sauces & Condiments',3.99,'each','','🥬','Nina',true),
(77,'Kirkland Organic Diced Tomatoes','grocery','Pantry','Sauces & Condiments',NULL,'','','🥬','Kirkland',true),
(78,'Kirkland Organic Tomato Sauce','grocery','Pantry','Sauces & Condiments',NULL,'','','🥬','Kirkland',true),
(79,'Frank''s RedHot Original','grocery','Pantry','Sauces & Condiments',6.99,'each','','🛒','Frank''s',true),
(80,'Heinz Tomato Ketchup','grocery','Pantry','Sauces & Condiments',4.99,'each','','🥬','Heinz',true),
(81,'Heinz Yellow Mustard','grocery','Pantry','Sauces & Condiments',5.99,'each','','🛒','Heinz',true),
(82,'Hellmann''s Real Mayonnaise','grocery','Pantry','Sauces & Condiments',6.99,'each','','🛒','Hellmann''s',true),
(83,'Tamam Tomato Paste jar','grocery','Pantry','Sauces & Condiments',4.99,'each','','🥬','Tamam',true),
(84,'Ragu Pasta Sauce assorted','grocery','Pantry','Sauces & Condiments',3.49,'each','','🛒','Ragu',true),
(85,'Prego Pasta Sauce assorted','grocery','Pantry','Sauces & Condiments',4.49,'each','','🛒','Prego',true),
(86,'Texas Pete Hot Sauce','grocery','Pantry','Sauces & Condiments',NULL,'','','🛒','Texas Pete',true),
(87,'Chick-fil-A Sauce bottle','grocery','Pantry','Sauces & Condiments',5.99,'each','','🛒','Chick-fil-A',true),
(88,'Biscoff Cookie Butter','grocery','Pantry','Sauces & Condiments',NULL,'','','🥛','Biscoff',true),
(89,'Jif Creamy Peanut Butter','grocery','Pantry','Sauces & Condiments',NULL,'','','🥛','Jif',true),
(90,'Member''s Mark Creamy Peanut Butter','grocery','Pantry','Sauces & Condiments',NULL,'','','🥛','Member''s Mark',true),
(91,'Rani Peanut Butter','grocery','Pantry','Sauces & Condiments',NULL,'','','🥛','Rani',true),
(92,'Goya Adobo assorted','grocery','Pantry','Sauces & Condiments',NULL,'','','🛒','Goya',true),
(93,'Del Monte Cut Green Beans','grocery','Pantry','Canned Goods',2.79,'each','','🛒','Del Monte',true),
(94,'Del Monte Whole Kernel Corn','grocery','Pantry','Canned Goods',2.99,'each','','🛒','Del Monte',true),
(95,'Del Monte Peas','grocery','Pantry','Canned Goods',NULL,'','','🛒','Del Monte',true),
(96,'Popeye Spinach','grocery','Pantry','Canned Goods',1.99,'each','','🛒','Popeye',true),
(97,'Veg-All Mixed Vegetables','grocery','Pantry','Canned Goods',1.69,'each','','🛒','Veg-All',true),
(98,'Sultan Canned vegetables assorted','grocery','Pantry','Canned Goods',1.49,'each','','🛒','Sultan',true),
(99,'Bush''s Beans assorted','grocery','Pantry','Canned Goods',NULL,'','','🛒','Bush''s',true),
(100,'Goya Beans assorted','grocery','Pantry','Canned Goods',1.89,'each','','🛒','Goya',true),
(101,'Goya Tuna / canned seafood assorted','grocery','Pantry','Canned Goods',NULL,'','','🛒','Goya',true),
(102,'Portofino Tuna','grocery','Pantry','Canned Goods',3.49,'each','','🛒','Portofino',true),
(103,'Kirkland Pink Salmon','grocery','Pantry','Canned Goods',3.49,'each','','🛒','Kirkland',true),
(104,'StarKist Tuna','grocery','Pantry','Canned Goods',NULL,'','','🛒','StarKist',true),
(105,'Shan Mutton Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(106,'Shan Sindhi Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(107,'Shan Fish Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(108,'Shan Bombay Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(109,'Shan Malay Chicken Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🍗','Shan',true),
(110,'Shan Karachi Beef Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🥩','Shan',true),
(111,'Shan Pilau Biryani','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(112,'Shan Chicken Handi','grocery','Pantry','Recipe Mix',2.29,'each','','🍗','Shan',true),
(113,'Shan Paya','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(114,'Shan Chicken Ginger','grocery','Pantry','Recipe Mix',2.29,'each','','🍗','Shan',true),
(115,'Shan Murgh Cholay','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(116,'Shan Daal Masala','grocery','Pantry','Recipe Mix',2.29,'each','','🧂','Shan',true),
(117,'Shan Chaat Masala','grocery','Pantry','Recipe Mix',2.29,'each','','🧂','Shan',true),
(118,'Shan Meat & Vegetable','grocery','Pantry','Recipe Mix',2.29,'each','','🥩','Shan',true),
(119,'Shan Shami Kabab','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(120,'Shan Chicken Curry','grocery','Pantry','Recipe Mix',2.29,'each','','🍗','Shan',true),
(121,'Shan Korma','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(122,'Shan Haleem','grocery','Pantry','Recipe Mix',2.29,'each','','🛒','Shan',true),
(123,'Mazola Corn Oil large','grocery','Pantry','Cooking Oil & Ghee',19.99,'each','','🛒','Mazola',true),
(124,'Ottavio Organic High Oleic Sunflower Oil','grocery','Pantry','Cooking Oil & Ghee',13.99,'each','','🛒','Ottavio',true),
(125,'Laxmi Cold Pressed Sesame Oil','grocery','Pantry','Cooking Oil & Ghee',NULL,'','','🛒','Laxmi',true),
(126,'Pompeian Extra Virgin Olive Oil','grocery','Pantry','Cooking Oil & Ghee',28.99,'each','','🛒','Pompeian',true),
(127,'Extra Virgin Olive Oil','grocery','Pantry','Cooking Oil & Ghee',26.99,'each','','🛒','Various',true),
(128,'Supremo Italiano Extra Virgin Olive Oil tin','grocery','Pantry','Cooking Oil & Ghee',39.99,'each','','🛒','Supremo Italiano',true),
(129,'Wesson Canola Oil','grocery','Pantry','Cooking Oil & Ghee',NULL,'','','🛒','Wesson',true),
(130,'Wesson Vegetable Oil','grocery','Pantry','Cooking Oil & Ghee',NULL,'','','🛒','Wesson',true),
(131,'Crisco Vegetable Shortening / oil','grocery','Pantry','Cooking Oil & Ghee',12.99,'each','','🛒','Crisco',true),
(132,'Kirkland Ghee','grocery','Pantry','Cooking Oil & Ghee',22.99,'each','','🛒','Kirkland',true),
(133,'Ghee jars','grocery','Pantry','Cooking Oil & Ghee',11.99,'each','','🛒','Various',true),
(134,'Ahmad Tea Cardamom Tea','grocery','Drinks','Tea & Coffee',6.99,'each','','🥤','Ahmad Tea',true),
(135,'Ahmad Tea English Tea No.1','grocery','Drinks','Tea & Coffee',6.99,'each','','🥤','Ahmad Tea',true),
(136,'Ahmad Tea Earl Grey Tea','grocery','Drinks','Tea & Coffee',6.99,'each','','🥤','Ahmad Tea',true),
(137,'Ahmad Tea Aromatic Earl Grey','grocery','Drinks','Tea & Coffee',8.99,'each','','🥤','Ahmad Tea',true),
(138,'Ahmad Tea Ceylon Tea','grocery','Drinks','Tea & Coffee',9.99,'each','','🥤','Ahmad Tea',true),
(139,'Ahmad Tea Imperial Blend','grocery','Drinks','Tea & Coffee',8.99,'each','','🥤','Ahmad Tea',true),
(140,'Ahmad Tea Kalami Assam','grocery','Drinks','Tea & Coffee',NULL,'','','🥤','Ahmad Tea',true),
(141,'Ahmad Tea English Breakfast','grocery','Drinks','Tea & Coffee',NULL,'','','🥤','Ahmad Tea',true),
(142,'Pocas Instant Honey Ginger Tea','grocery','Drinks','Tea & Coffee',6.99,'each','','🥤','Pocas',true),
(143,'China Slim Tea Herbal Tea Delight','grocery','Drinks','Tea & Coffee',NULL,'','','🥤','China Slim Tea',true),
(144,'3 Ballerina Herbal Tea','grocery','Drinks','Tea & Coffee',NULL,'','','🥤','3 Ballerina',true),
(145,'Green Fresh Herbal Dieter''s Tea','grocery','Drinks','Tea & Coffee',5.99,'each','','🥤','Green Fresh',true),
(146,'Jacobs Kronung Coffee','grocery','Drinks','Tea & Coffee',NULL,'','','🥤','Jacobs',true),
(147,'Nescafe Instant Coffee','grocery','Drinks','Tea & Coffee',13.99,'each','','🥤','Nescafe',true),
(148,'Maxwell House Coffee','grocery','Drinks','Tea & Coffee',19.99,'each','','🥤','Maxwell House',true),
(149,'Folgers Coffee','grocery','Drinks','Tea & Coffee',NULL,'','','🥤','Folgers',true),
(150,'Tri-C Instant Drink Powder assorted','grocery','Drinks','Drinks',10.99,'each','','🥤','Tri-C',true),
(151,'Vimto Fruit Cordial','grocery','Drinks','Drinks',5.99,'each','','🥤','Vimto',true),
(152,'Frooti Mango / fruit drink large','grocery','Drinks','Drinks',5.99,'each','','🥤','Frooti',true),
(153,'Arabican Fruit drink cartons assorted','grocery','Drinks','Drinks',6.99,'each','','🥤','Arabican',true),
(154,'Vita Malt Classic','grocery','Drinks','Drinks',8.99,'each','','🥤','Vita Malt',true),
(155,'Vita Malt Ginger','grocery','Drinks','Drinks',8.99,'each','','🥤','Vita Malt',true),
(156,'Power Malt Energy drink','grocery','Drinks','Drinks',8.99,'each','','🥤','Power Malt',true),
(157,'Kesar Mango Pulp canned','grocery','Drinks','Drinks',4.29,'each','','🥤','Kesar',true),
(158,'Bird''s Custard Powder','grocery','Drinks','Drinks',4.99,'each','','🥤','Bird''s',true),
(159,'Langers Organic Mango Nectar gallon','grocery','Drinks','Drinks',NULL,'','','🥤','Langers',true),
(160,'Fanta Orange glass bottle case','grocery','Drinks','Drinks',NULL,'','','🥤','Fanta',true),
(161,'Jarritos Case assorted','grocery','Drinks','Drinks',NULL,'','','🥤','Jarritos',true),
(162,'Coca-Cola 2 liter','grocery','Drinks','Drinks',NULL,'','','🥤','Coca-Cola',true),
(163,'Sprite 2 liter','grocery','Drinks','Drinks',NULL,'','','🥤','Sprite',true),
(164,'Pepsi 2 liter','grocery','Drinks','Drinks',NULL,'','','🥤','Pepsi',true),
(165,'Fanta 2 liter','grocery','Drinks','Drinks',NULL,'','','🥤','Fanta',true),
(166,'Fiji Bottled water','grocery','Drinks','Drinks',1.59,'each','','🥤','Fiji',true),
(167,'Deer Park Bottled water','grocery','Drinks','Drinks',0.99,'each','','🥤','Deer Park',true),
(168,'Evian Bottled water','grocery','Drinks','Drinks',2.19,'each','','🥤','Evian',true),
(169,'Acqua Panna Bottled water','grocery','Drinks','Drinks',0.89,'each','','🥤','Acqua Panna',true),
(170,'Dasani Bottled water','grocery','Drinks','Drinks',2.49,'each','','🥤','Dasani',true),
(171,'Aquafina Bottled water','grocery','Drinks','Drinks',NULL,'','','🥤','Aquafina',true),
(172,'Powerade Assorted flavors','grocery','Drinks','Drinks',1.59,'each','','🥤','Powerade',true),
(173,'Gatorade Assorted flavors','grocery','Drinks','Drinks',1.59,'each','','🥤','Gatorade',true),
(174,'Gatorade Larger bottle assorted','grocery','Drinks','Drinks',2.49,'each','','🥤','Gatorade',true),
(175,'Perrier Glass bottle','grocery','Drinks','Drinks',2.69,'each','','🥤','Perrier',true),
(176,'Topo Chico Glass bottle','grocery','Drinks','Drinks',2.49,'each','','🥤','Topo Chico',true),
(177,'Mogu Mogu Assorted flavors','grocery','Drinks','Drinks',1.89,'each','','🥤','Mogu Mogu',true),
(178,'Coca-Cola Can','grocery','Drinks','Drinks',1.09,'each','','🥤','Coca-Cola',true),
(179,'Mountain Dew Can','grocery','Drinks','Drinks',1.09,'each','','🥤','Mountain Dew',true),
(180,'Fanta Can assorted','grocery','Drinks','Drinks',1.09,'each','','🥤','Fanta',true),
(181,'Red Bull Can','grocery','Drinks','Drinks',2.69,'each','','🥤','Red Bull',true),
(182,'Coca-Cola 20 oz bottle','grocery','Drinks','Drinks',1.99,'each','','🥤','Coca-Cola',true),
(183,'Sprite 20 oz bottle','grocery','Drinks','Drinks',1.99,'each','','🥤','Sprite',true),
(184,'Pepsi 20 oz bottle','grocery','Drinks','Drinks',1.99,'each','','🥤','Pepsi',true),
(185,'Dr Pepper Bottle/can','grocery','Drinks','Drinks',1.09,'each','','🥤','Dr Pepper',true),
(186,'7UP 20 oz bottle','grocery','Drinks','Drinks',1.99,'each','','🥤','7UP',true),
(187,'Fanta 20 oz bottle assorted','grocery','Drinks','Drinks',1.99,'each','','🥤','Fanta',true),
(188,'Sunkist Bottle/can assorted','grocery','Drinks','Drinks',1.09,'each','','🥤','Sunkist',true),
(189,'Jarritos Assorted glass bottles','grocery','Drinks','Drinks',1.79,'each','','🥤','Jarritos',true),
(190,'FOCO Coconut Juice','grocery','Drinks','Drinks',2.79,'each','','🥤','FOCO',true),
(191,'FOCO Tamarind Drink','grocery','Drinks','Drinks',2.79,'each','','🥤','FOCO',true),
(192,'Jumex Coconut Water','grocery','Drinks','Drinks',1.29,'each','','🥤','Jumex',true),
(193,'FOCO Coconut Water','grocery','Drinks','Drinks',1.29,'each','','🥤','FOCO',true),
(194,'Farmer''s Aloe Vera Aloe Vera Drink','grocery','Drinks','Drinks',NULL,'','','🥤','Farmer''s Aloe Vera',true),
(195,'Tropical Fantasy Assorted flavors','grocery','Drinks','Drinks',1.49,'each','','🥤','Tropical Fantasy',true),
(196,'Ocean Spray Cranberry Juice','grocery','Drinks','Drinks',4.99,'each','','🥤','Ocean Spray',true),
(197,'Kirkland Organic Lemonade','grocery','Drinks','Drinks',4.99,'each','','🥤','Kirkland',true),
(198,'Veryfine Fruit Punch','grocery','Drinks','Drinks',6.99,'each','','🥤','Veryfine',true),
(199,'Langers Tart Cherry Pineapple','grocery','Drinks','Drinks',6.5,'each','','🥤','Langers',true),
(200,'Mott''s 100% Apple Juice','grocery','Drinks','Drinks',4.99,'each','','🥤','Mott''s',true),
(201,'Hawaiian Punch Large jug','grocery','Drinks','Drinks',4.99,'each','','🥤','Hawaiian Punch',true),
(202,'Langers Mango Nectar','grocery','Drinks','Drinks',NULL,'','','🥤','Langers',true),
(203,'Sunberry Farms Guava Nectar','grocery','Drinks','Drinks',NULL,'','','🥤','Sunberry Farms',true),
(204,'Sunberry Farms Orange Passion Nectar','grocery','Drinks','Drinks',NULL,'','','🥤','Sunberry Farms',true),
(205,'Great Value Sour Bears Candy','grocery','Snacks','Snacks',NULL,'','','🍬','Great Value',true),
(206,'Great Value Cherry Gummies','grocery','Snacks','Snacks',NULL,'','','🍬','Great Value',true),
(207,'Great Value Peach Rings','grocery','Snacks','Snacks',NULL,'','','🍬','Great Value',true),
(208,'Great Value Gummy Sharks','grocery','Snacks','Snacks',NULL,'','','🍬','Great Value',true),
(209,'Great Value Gummy Worms','grocery','Snacks','Snacks',NULL,'','','🍬','Great Value',true),
(210,'Gushers Variety Pack','grocery','Snacks','Snacks',NULL,'','','🍬','Gushers',true),
(211,'Kopiko Coffee Candy assorted','grocery','Snacks','Snacks',2.99,'each','','🥤','Kopiko',true),
(212,'Al Safa Crispy Rice Squares','grocery','Snacks','Snacks',2.49,'each','','🍚','Al Safa',true),
(213,'Biscoff Cookies','grocery','Snacks','Snacks',9.99,'each','','🍬','Biscoff',true),
(214,'Cake Rusk Assorted boxes','grocery','Snacks','Snacks',6.99,'each','','🍬','Cake Rusk',true),
(215,'Parle-G / assorted Biscuits','grocery','Snacks','Snacks',NULL,'','','🍬','Parle-G / assorted',true),
(216,'Cream Biscuits assorted','grocery','Snacks','Snacks',NULL,'','','🥛','Various',true),
(217,'Baklava / boxed sweets','grocery','Snacks','Snacks',18.99,'each','','🍬','Various',true),
(218,'Dates / sweets gift box','grocery','Snacks','Snacks',NULL,'','','🍬','Various',true),
(219,'Clorox Disinfecting Bleach','household','Household','Cleaning & Disposable',4.99,'each','','🧼','Clorox',true),
(220,'Lysol Power Clinging Gel','household','Household','Cleaning & Disposable',4.99,'each','','🛒','Lysol',true),
(221,'Kleenex Facial Tissue','household','Household','Cleaning & Disposable',NULL,'','','🧼','Kleenex',true),
(222,'Pledge Furniture Polish','household','Household','Cleaning & Disposable',3.99,'each','','🛒','Pledge',true),
(223,'Windex Glass Cleaner','household','Household','Cleaning & Disposable',5.99,'each','','🧼','Windex',true),
(224,'Dove Bar Soap assorted','household','Household','Cleaning & Disposable',1.69,'each','','🧼','Dove',true),
(225,'Irish Spring Bar Soap','household','Household','Cleaning & Disposable',1.39,'each','','🧼','Irish Spring',true),
(226,'Lux Bar Soap','household','Household','Cleaning & Disposable',1.69,'each','','🧼','Lux',true),
(227,'Palmolive Bar Soap assorted','household','Household','Cleaning & Disposable',NULL,'','','🧼','Palmolive',true),
(228,'Tide Liquid Laundry Detergent','household','Household','Cleaning & Disposable',16.99,'each','','🧼','Tide',true),
(229,'Tide Powder Laundry Detergent','household','Household','Cleaning & Disposable',NULL,'','','🧂','Tide',true),
(230,'Gain Liquid Laundry Detergent','household','Household','Cleaning & Disposable',NULL,'','','🧼','Gain',true),
(231,'Kirkland UltraClean Laundry Detergent','household','Household','Cleaning & Disposable',25.0,'each','','🧼','Kirkland',true),
(232,'Downy Fabric Softener','household','Household','Cleaning & Disposable',16.99,'each','','🛒','Downy',true),
(233,'Snuggle Fabric Softener','household','Household','Cleaning & Disposable',16.99,'each','','🛒','Snuggle',true),
(234,'All Laundry Detergent','household','Household','Cleaning & Disposable',NULL,'','','🧼','All',true),
(235,'Ajax Dish Liquid assorted','household','Household','Cleaning & Disposable',NULL,'','','🛒','Ajax',true),
(236,'Joy Dish Liquid','household','Household','Cleaning & Disposable',1.99,'each','','🛒','Joy',true),
(237,'Dawn Platinum Dish Soap','household','Household','Cleaning & Disposable',NULL,'','','🧼','Dawn',true),
(238,'Member''s Mark Liquid Dish Soap','household','Household','Cleaning & Disposable',NULL,'','','🧼','Member''s Mark',true),
(239,'Glad Trash Bags','household','Household','Cleaning & Disposable',NULL,'','','🧼','Glad',true),
(240,'Ziploc Freezer Bags','household','Household','Cleaning & Disposable',6.99,'each','','🧼','Ziploc',true),
(241,'Kirkland Freezer Quart Plus Bags','household','Household','Cleaning & Disposable',3.99,'each','','🧼','Kirkland',true),
(242,'GoodSense Sandwich Bags','household','Household','Cleaning & Disposable',1.29,'each','','🧼','GoodSense',true),
(243,'POM Paper Towels','household','Household','Cleaning & Disposable',17.99,'each','','🛒','POM',true),
(244,'Bath Tissue Large Roll Pack','household','Household','Cleaning & Disposable',15.99,'each','','🧼','Bath Tissue',true),
(245,'Hefty Foam Plates / bowls assorted','household','Household','Cleaning & Disposable',NULL,'','','🧼','Hefty',true),
(246,'Member''s Mark White Plastic Cutlery Packets','household','Household','Cleaning & Disposable',NULL,'','','🛒','Member''s Mark',true),
(247,'Member''s Mark Plastic Spoons','household','Household','Cleaning & Disposable',NULL,'','','🛒','Member''s Mark',true),
(248,'Foam Takeout Containers','household','Household','Cleaning & Disposable',NULL,'','','🛒','Various',true),
(249,'Disposable Plates/Bowls','household','Household','Cleaning & Disposable',NULL,'','','🧼','Various',true),
(250,'Aluminum Pans','household','Household','Cleaning & Disposable',1.69,'each','','🛒','Various',true),
(251,'Sterno Butane Fuel Cartridge','household','Household','Cleaning & Disposable',2.69,'each','','🛒','Sterno',true),
(252,'Diapers sizes 1–7 bulk packs','baby','Baby','Diapers',NULL,'','','👶','Various',true),
(253,'Huggies Huggies Plus','baby','Baby','Diapers',NULL,'','','👶','Huggies',true),
(254,'Training pants / pull-ups','baby','Baby','Training Pants',NULL,'','','👶','Various',true),
(255,'Limes','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(256,'Oranges','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(257,'Apples','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(258,'Red Onions','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(259,'Potatoes','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(260,'Tomatoes','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(261,'Garlic','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(262,'Yellow Onions','grocery','Produce','Fresh Produce',NULL,'','','🥬','Fresh',true),
(263,'Member''s Mark Commercial Airpot','household','Household','Kitchen & Home',NULL,'','','🛒','Member''s Mark',true),
(264,'Aluminum Cooking Pot Set','household','Household','Kitchen & Home',NULL,'','','🛒','Various',true),
(265,'Vacuum Flask','household','Household','Kitchen & Home',25.0,'each','','🛒','Various',true),
(266,'Always Electric Kettle','household','Household','Kitchen & Home',20.0,'each','','🛒','Always',true),
(267,'Aluminum Tea Kettle','household','Household','Kitchen & Home',NULL,'','','🥤','Various',true),
(268,'Acrylic Mosque Frame / decor','household','Household','Kitchen & Home',NULL,'','','🛒','Various',true),
(269,'Mortar & Pestle','household','Household','Kitchen & Home',14.0,'each','','🛒','Various',true),
(270,'Kontos Roghani Naan','grocery','Refrigerated','Dairy / Bread / Dates',3.99,'each','','🫓','Kontos',true),
(271,'Kontos Pocketless Pita','grocery','Refrigerated','Dairy / Bread / Dates',3.99,'each','','🫓','Kontos',true),
(272,'Kontos Massala Naan','grocery','Refrigerated','Dairy / Bread / Dates',4.99,'each','','🫓','Kontos',true),
(273,'Flatbread / wraps','grocery','Refrigerated','Dairy / Bread / Dates',1.99,'each','','🫓','Various',true),
(274,'Panini Bread','grocery','Refrigerated','Dairy / Bread / Dates',4.99,'each','','🫓','Various',true),
(275,'Lurpak Unsalted Butter','grocery','Refrigerated','Dairy / Bread / Dates',2.99,'each','','🥛','Lurpak',true),
(276,'Kirkland Cream Cheese','grocery','Refrigerated','Dairy / Bread / Dates',2.99,'each','','🥛','Kirkland',true),
(277,'Kirkland Butter sticks','grocery','Refrigerated','Dairy / Bread / Dates',4.79,'each','','🥛','Kirkland',true),
(278,'Puck Cream Cheese Spread','grocery','Refrigerated','Dairy / Bread / Dates',6.99,'each','','🥛','Puck',true),
(279,'Kiri Cheese Portions','grocery','Refrigerated','Dairy / Bread / Dates',3.99,'each','','🥛','Kiri',true),
(280,'Kraft Parmesan Cheese','grocery','Refrigerated','Dairy / Bread / Dates',7.99,'each','','🥛','Kraft',true),
(281,'Land O Lakes Heavy Whipping Cream','grocery','Refrigerated','Dairy / Bread / Dates',6.99,'each','','🥛','Land O Lakes',true),
(282,'Land O Lakes Half & Half','grocery','Refrigerated','Dairy / Bread / Dates',3.49,'each','','🛒','Land O Lakes',true),
(283,'Borden Cultured Buttermilk','grocery','Refrigerated','Dairy / Bread / Dates',3.89,'each','','🥛','Borden',true),
(284,'Nesquik Flavored Milk','grocery','Refrigerated','Dairy / Bread / Dates',2.69,'each','','🥛','Nesquik',true),
(285,'Shamrock Farms Yogurt Drink','grocery','Refrigerated','Dairy / Bread / Dates',2.49,'each','','🥤','Shamrock Farms',true),
(286,'Date Crown Dates boxed','grocery','Refrigerated','Dairy / Bread / Dates',NULL,'','','🛒','Date Crown',true),
(287,'Ziyad Medjool Dates','grocery','Refrigerated','Dairy / Bread / Dates',NULL,'','','🛒','Ziyad',true),
(288,'Popping Boba Assorted Cups','grocery','Refrigerated','Dairy / Bread / Dates',2.99,'each','','🛒','Popping Boba',true),
(289,'Al Safa Chicken Tenders','grocery','Frozen','Frozen Food',16.99,'each','','🍗','Al Safa',true),
(290,'Al Safa Chicken Breast Strips','grocery','Frozen','Frozen Food',10.99,'each','','🍗','Al Safa',true),
(291,'Al Safa Chicken Patties','grocery','Frozen','Frozen Food',7.99,'each','','🍗','Al Safa',true),
(292,'Al Safa Beef Meatballs','grocery','Frozen','Frozen Food',14.99,'each','','🥩','Al Safa',true),
(293,'Al Safa Beef Gyro Slices','grocery','Frozen','Frozen Food',14.99,'each','','🥩','Al Safa',true),
(294,'Al Safa Chicken Seekh Kebab','grocery','Frozen','Frozen Food',13.49,'each','','🍗','Al Safa',true),
(295,'Al Safa Beef Cheese Poutine','grocery','Frozen','Frozen Food',16.99,'each','','🥩','Al Safa',true),
(296,'Delight Valley Halal Chicken Wing Sections','grocery','Frozen','Frozen Food',26.99,'each','','🍗','Delight Valley',true),
(297,'Delight Valley Halal Chicken Breast Nuggets','grocery','Frozen','Frozen Food',21.99,'each','','🍗','Delight Valley',true),
(298,'Delight Valley Chicken Tenderloin Fillets','grocery','Frozen','Frozen Food',25.99,'each','','🍗','Delight Valley',true),
(299,'Delight Valley Breaded Chicken Breast','grocery','Frozen','Frozen Food',28.0,'each','','🍗','Delight Valley',true),
(300,'Midamar Chicken Tenders','grocery','Frozen','Frozen Food',16.99,'each','','🍗','Midamar',true),
(301,'Midamar Chicken Breast Patties','grocery','Frozen','Frozen Food',15.99,'each','','🍗','Midamar',true),
(302,'Mezban Beef Seekh Kabab','grocery','Frozen','Frozen Food',12.99,'each','','🥩','Mezban',true),
(303,'Mezban Chicken Samosa','grocery','Frozen','Frozen Food',11.99,'each','','🍗','Mezban',true),
(304,'Mezban Beef Samosa','grocery','Frozen','Frozen Food',11.99,'each','','🥩','Mezban',true),
(305,'Mezban Chicken Tikka','grocery','Frozen','Frozen Food',11.99,'each','','🍗','Mezban',true),
(306,'Colonel Kababz Vegetable Spring Roll','grocery','Frozen','Frozen Food',5.99,'each','','❄️','Colonel Kababz',true),
(307,'Royal Asia Vegetable Spring Rolls with Edamame','grocery','Frozen','Frozen Food',9.5,'each','','❄️','Royal Asia',true),
(308,'Ziyad Premium Kufta Kabob','grocery','Frozen','Frozen Food',9.99,'each','','❄️','Ziyad',true),
(309,'Kawan Puff Pastry','grocery','Frozen','Frozen Food',2.99,'each','','❄️','Kawan',true),
(310,'La Fe Guanabana / Soursop Pulp','grocery','Frozen','Frozen Food',4.99,'each','','❄️','La Fe',true),
(311,'Ore-Ida Extra Crispy Fries','grocery','Frozen','Frozen Food',11.99,'each','','❄️','Ore-Ida',true),
(312,'French Fries / Fry Stix','grocery','Frozen','Frozen Food',18.99,'each','','❄️','Various',true),
(313,'Peas','grocery','Frozen','Frozen Food',6.99,'each','','❄️','Various',true),
(314,'Peas & Carrots','grocery','Frozen','Frozen Food',6.99,'each','','❄️','Various',true),
(315,'Riverside Farm Premium Broccoli Normandy','grocery','Frozen','Frozen Food',NULL,'','','❄️','Riverside Farm',true),
(316,'Riverside Farm Italian Blend Vegetables','grocery','Frozen','Frozen Food',NULL,'','','❄️','Riverside Farm',true),
(317,'Cut Okra','grocery','Frozen','Frozen Food',2.99,'each','','❄️','Various',true),
(318,'Chopped Spinach','grocery','Frozen','Frozen Food',NULL,'','','❄️','Various',true),
(319,'Vaseline Aloe Soothe Lotion','beauty','Health & Beauty','Personal Care',5.99,'each','','🧴','Vaseline',true),
(320,'Vaseline Nourishing Argan Oil Lotion','beauty','Health & Beauty','Personal Care',5.99,'each','','🧴','Vaseline',true),
(321,'Vaseline Dry Skin Repair Lotion','beauty','Health & Beauty','Personal Care',5.99,'each','','🧴','Vaseline',true),
(322,'Head & Shoulders Shampoo assorted','beauty','Health & Beauty','Personal Care',6.99,'each','','🧴','Head & Shoulders',true),
(323,'Dabur Amla Hair Oil','beauty','Health & Beauty','Personal Care',NULL,'','','🧴','Dabur Amla',true),
(324,'Nexxus 48 HR Hair Treatment','beauty','Health & Beauty','Personal Care',NULL,'','','🧴','Nexxus',true),
(325,'Pantene Hair Care Products','beauty','Health & Beauty','Personal Care',NULL,'','','🧴','Pantene',true),
(326,'Sultan Henna / Hair Color','beauty','Health & Beauty','Personal Care',NULL,'','','🧴','Sultan',true),
(327,'Duracell Assorted Batteries','beauty','Health & Beauty','Personal Care',NULL,'','','🧴','Duracell',true),
(328,'Assorted Prayer Rugs','clothing','Clothing & Gifts','Clothing / Cultural',NULL,'','','🧕','Various',true),
(329,'Men''s Thobe / Long Garment','clothing','Clothing & Gifts','Clothing / Cultural',NULL,'','','🧕','Various',true),
(330,'Abaya / Dresses','clothing','Clothing & Gifts','Clothing / Cultural',16.0,'each','','🧕','Various',true),
(331,'Dirac / Open Dress','clothing','Clothing & Gifts','Clothing / Cultural',NULL,'','','🛒','Various',true),
(332,'Cimamo / Assorted Garment','clothing','Clothing & Gifts','Clothing / Cultural',12.0,'each','','🧕','Various',true),
(333,'Scarves / Wrapped Textiles','clothing','Clothing & Gifts','Clothing / Cultural',NULL,'','','🧕','Various',true),
(9001,'Lamb','meat','Lamb','Fresh Meat',12.99,'/ lb','product-images/lamb_shoulder.jpg','🐑','Makka Halal Meat',true),
(9002,'Goat','meat','Goat','Fresh Meat',12.99,'/ lb','product-images/goat_shoulder.jpg','🐐','Makka Halal Meat',true),
(9003,'Leg - Goat or Lamb','meat','Lamb','Fresh Meat',15.99,'/ lb','product-images/lamb_leg.jpg','🥩','Makka Halal Meat',true),
(9004,'Steak - Lamb or Goat','meat','Lamb','Fresh Meat',15.99,'/ lb','product-images/lamb_steak.jpg','🥩','Makka Halal Meat',true),
(9005,'Liver - Goat or Lamb','meat','Goat','Fresh Meat',11.99,'/ lb','product-images/lamb_liver.jpg','🥩','Makka Halal Meat',true),
(9006,'Liver - Goat or Lamb (Cut)','meat','Goat','Fresh Meat',12.99,'/ lb','product-images/lamb_liver.jpg','🔪','Makka Halal Meat',true),
(9007,'Frozen Goat or Frozen Lamb','grocery','Frozen','Frozen Meat',6.99,'/ lb','product-images/goat_shoulder.jpg','❄️','Makka Halal Meat',true),
(9008,'Lamb Chop or Goat Chop','meat','Lamb','Fresh Meat',14.99,'/ lb','product-images/lamb_chops.jpg','🥩','Makka Halal Meat',true),
(9009,'Goat Feet (Paya)','meat','Goat','Fresh Meat',6.99,'/ lb','product-images/goat_shank.jpg','🐐','Makka Halal Meat',true),
(9010,'Frozen Boneless Lamb Leg','grocery','Frozen','Frozen Meat',11.99,'/ lb','product-images/lamb_leg.jpg','❄️','Makka Halal Meat',true),
(9011,'Frozen Goat Leg','grocery','Frozen','Frozen Meat',10.99,'/ lb','product-images/goat_leg.jpg','❄️','Makka Halal Meat',true),
(9012,'Frozen Lamb Leg','grocery','Frozen','Frozen Meat',10.99,'/ lb','product-images/lamb_leg.jpg','❄️','Makka Halal Meat',true),
(9013,'Frozen Lamb','grocery','Frozen','Frozen Meat',7.99,'/ lb','product-images/lamb_shoulder.jpg','❄️','Makka Halal Meat',true),
(9014,'Frozen Lamb Import Shank','grocery','Frozen','Frozen Meat',6.99,'/ lb','product-images/lamb_shank.jpg','❄️','Makka Halal Meat',true),
(9020,'Beef Ribs (Bone-In)','meat','Beef','Fresh Meat',5.99,'/ lb','product-images/beef_ribs.jpg','🥩','Makka Halal Meat',true),
(9021,'Beef Shoulder (Bone-In)','meat','Beef','Fresh Meat',5.49,'/ lb','product-images/beef_shoulder.jpg','🥩','Makka Halal Meat',true),
(9022,'Beef Back Leg (Bone-In)','meat','Beef','Fresh Meat',6.99,'/ lb','product-images/beef_back_leg.jpg','🥩','Makka Halal Meat',true),
(9023,'Beef Stew','meat','Beef','Fresh Meat',8.99,'/ lb','product-images/beef_stew.jpg','🥩','Makka Halal Meat',true),
(9024,'Ground Beef','meat','Beef','Fresh Meat',8.99,'/ lb','product-images/ground_beef.jpg','🥩','Makka Halal Meat',true),
(9025,'Beef Steak','meat','Beef','Fresh Meat',7.99,'/ lb','product-images/beef_steak.jpg','🥩','Makka Halal Meat',true),
(9026,'Beef Odkac (Muqamad)','meat','Beef','Fresh Meat',9.99,'/ lb','product-images/beef_odkac.jpg','🥩','Makka Halal Meat',true),
(9027,'Beef Fillet','meat','Beef','Fresh Meat',11.99,'/ lb','product-images/beef_fillet.jpg','🥩','Makka Halal Meat',true),
(9028,'Oxtail','meat','Beef','Fresh Meat',10.99,'/ lb','product-images/oxtail.jpg','🥩','Makka Halal Meat',true),
(9029,'Beef Tongue','meat','Beef','Fresh Meat',7.99,'/ lb','product-images/beef_tongue.jpg','🥩','Makka Halal Meat',true),
(9030,'Beef Liver','meat','Beef','Fresh Meat',5.0,'/ lb','product-images/beef_liver.jpg','🥩','Makka Halal Meat',true),
(9031,'Beef T-Bone Steak','meat','Beef','Fresh Meat',6.99,'/ lb','product-images/beef_steak.jpg','🥩','Makka Halal Meat',true),
(9032,'Beef Short Ribs','meat','Beef','Fresh Meat',5.49,'/ lb','product-images/beef_ribs.jpg','🥩','Makka Halal Meat',true),
(9040,'Chicken Drumsticks','meat','Chicken','Poultry',1.69,'/ lb','product-images/drumsticks.jpg','🍗','Makka Halal Meat',true),
(9041,'Chicken Leg Quarters','meat','Chicken','Poultry',1.19,'/ lb','product-images/leg_quarters.jpg','🍗','Makka Halal Meat',true),
(9042,'Cut Chicken Wings','meat','Chicken','Poultry',4.29,'/ lb','product-images/cut_wings.jpg','🍗','Makka Halal Meat',true),
(9043,'Whole Chicken','meat','Chicken','Poultry',7.99,'each','product-images/whole_chicken.jpg','🍗','Makka Halal Meat',true),
(9044,'Boneless Chicken Breast','meat','Chicken','Poultry',4.99,'/ lb','product-images/boneless_chicken_breast.jpg','🍗','Makka Halal Meat',true),
(9045,'Ground Chicken Breast','meat','Chicken','Poultry',5.99,'/ lb','product-images/ground_chicken.jpg','🍗','Makka Halal Meat',true),
(9046,'Chicken Tenders','meat','Chicken','Poultry',5.99,'/ lb','product-images/chicken_tenders.jpg','🍗','Makka Halal Meat',true),
(9050,'King Fish','meat','Fish','Seafood',8.99,'/ lb','product-images/king_fish.jpg','🐟','Makka Halal Meat',true),
(9051,'Tilapia','meat','Fish','Seafood',5.99,'/ lb','product-images/tilapia.jpg','🐟','Makka Halal Meat',true),
(9052,'Chum Salmon Fillet','meat','Fish','Seafood',11.99,'/ lb','product-images/salmon_fillet.jpg','🐟','Makka Halal Meat',true),
(9060,'Camel Boneless','meat','Camel','Fresh Meat',14.99,'/ lb','product-images/camel_boneless.jpg','🐪','Makka Halal Meat',true),
(9061,'Camel Liver','meat','Camel','Fresh Meat',8.99,'/ lb','product-images/camel_liver.jpg','🐪','Makka Halal Meat',true),
(9062,'Camel Odkac','meat','Camel','Fresh Meat',15.99,'/ lb','product-images/camel_stew.jpg','🐪','Makka Halal Meat',true),
(9063,'Camel Hump Fat','meat','Camel','Fresh Meat',4.99,'/ lb','product-images/camel_hump.jpg','🐪','Makka Halal Meat',true),
(9064,'Camel Kidney','meat','Camel','Fresh Meat',4.99,'/ lb','product-images/camel_kidney.jpg','🐪','Makka Halal Meat',true),
(9065,'Camel Bone-In Short Ribs','meat','Camel','Fresh Meat',5.99,'/ lb','product-images/camel_ribs.jpg','🐪','Makka Halal Meat',true),
(9070,'Turkey Breast','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_turkey.jpg','🥪','Makka Halal Meat',true),
(9071,'Smoked Turkey Breast','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_turkey.jpg','🥪','Makka Halal Meat',true),
(9072,'Turkey Bacon','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_turkey.jpg','🥪','Makka Halal Meat',true),
(9073,'Turkey Pastrami','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_turkey.jpg','🥪','Makka Halal Meat',true),
(9074,'Turkey Ham','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_turkey.jpg','🥪','Makka Halal Meat',true),
(9075,'Roasted Beef Deli','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_beef.jpg','🥪','Makka Halal Meat',true),
(9076,'Corned Beef Deli','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_beef.jpg','🥪','Makka Halal Meat',true),
(9077,'Beef Salami','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_beef.jpg','🥪','Makka Halal Meat',true),
(9078,'Beef Bologna','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_beef.jpg','🥪','Makka Halal Meat',true),
(9079,'Beef Pastrami','meat','Deli','Deli Meat',8.99,'/ lb','product-images/deli_beef.jpg','🥪','Makka Halal Meat',true)
on conflict (id) do nothing;
